Iter9
andrey67895/new_test_go_y_practicum pull request #11
Opened 2024-04-29 10:56 UTC by andrey67895

2024-04-29 16:22 UTC, Perederey requested changes
Много мелких ошибок, надо переделать.

Но в целом, отличная работа.

2024-04-29 16:22 UTC, Perederey commented on cmd/agent/main.go
>  	"flag"
Надо сделать сортировку через goimports

2024-04-29 16:22 UTC, Perederey commented on cmd/server/main.go
> +var storeInterval int
Лучше бы в конфиг хранить, а не тут

2024-04-29 16:22 UTC, Perederey commented on cmd/server/main.go
> +	if envStoreInterval := os.Getenv("STORE_INTERVAL"); envStoreInterval != "" {
Это не часть Main, а часть config

2024-04-29 16:22 UTC, Perederey commented on cmd/server/main.go
>  	r.Post("/update/{type}/{name}/{value}", handlers.MetHandler)
Router можно перенести в router.go

2024-04-29 16:22 UTC, Perederey commented on cmd/server/main.go
> +func CreateData(fname string) {
Очень общее название функции

2024-04-29 16:22 UTC, Perederey commented on cmd/server/main.go
> +		time.Sleep(time.Duration(storeInterval) * time.Second)
Надо передать через ticker, timesleep тут не нужен.

Плюс лучше разделить логику сохранения и интервальное сохранение

2024-04-29 16:22 UTC, Perederey commented on internal/handlers/JsonHandler.go
> +	tModel := model.JSONMetrics{}
var tModel model.JSONMetrics

2024-05-30 20:31 UTC, andrey67895 commented on cmd/agent/main.go
>  	"flag"
Исправил

2024-05-30 20:42 UTC, andrey67895 commented on cmd/server/main.go
> +var storeInterval int
Вынес отдельно

2024-05-30 20:42 UTC, andrey67895 commented on cmd/server/main.go
> +	if envStoreInterval := os.Getenv("STORE_INTERVAL"); envStoreInterval != "" {
Вынес отдельно

2024-05-30 20:45 UTC, andrey67895 commented on cmd/server/main.go
>  	r.Post("/update/{type}/{name}/{value}", handlers.MetHandler)
Исправил

2024-05-31 03:45 UTC, andrey67895 commented on cmd/server/main.go
> +func CreateData(fname string) {
Исправил

2024-05-31 03:49 UTC, andrey67895 commented on cmd/server/main.go
> +	if typeMet == "gauge" {
Исправил

2024-05-31 03:58 UTC, andrey67895 commented on cmd/server/main.go
> +				println(err.Error())
Исправил

2024-05-31 04:11 UTC, andrey67895 commented on cmd/server/main.go
> +		time.Sleep(time.Duration(storeInterval) * time.Second)
Исправил

2024-05-31 04:13 UTC, andrey67895 commented on internal/handlers/JsonHandler.go
> +	tModel := model.JSONMetrics{}
Исправил

2024-05-31 04:14 UTC, andrey67895 commented on internal/handlers/Logger.go
> +	sugar := *logger.Sugar()
Вроде внешнюю библиотеку нужно было использовать, возможно не правильно понял вопрос

2024-05-31 04:25 UTC, andrey67895 commented on internal/handlers/JsonHandler.go
> +	if typeMet == "gauge" {
Исправил

2024-05-31 04:25 UTC, andrey67895 commented on internal/handlers/Logger.go
> +		sugar.Infoln(
Исправил

2024-05-31 04:25 UTC, andrey67895 commented on internal/helpers/CompressHelper.go
> +
Исправил

2024-05-31 04:25 UTC, andrey67895 commented on internal/model/JsonMemModel.go
> +func (e *JSONMetrics) SetValue(v float64) {
Исправил

2024-05-31 07:34 UTC, Perederey approved these changes
В целом ок, но есть то, что можно улучшить. Так как тесты проходят, то я работу приму.

Но попробуй сконцентрироваться на рефакторинге, посмотри что такое чистая архитектура и как можно разбить твой код на сервисы, хендлеры, использовать интерфейсы для работы

2024-05-31 07:34 UTC, Perederey commented on cmd/agent/main.go
> +	client := &http.Client{}
Ты создаешь клиента при каждом вызове, так делать не надо. Нал осознать клиента раз и передавать его сюда.

2024-05-31 07:34 UTC, Perederey commented on cmd/agent/main.go
> +	tModel, _ := json.Marshal(tJSON)
Нужно делать проверку на ошибки

2024-05-31 07:34 UTC, Perederey commented on cmd/agent/main.go
> +	client := &http.Client{}
Много повторного кода, нужно сделать рефакторинг

2024-05-31 07:34 UTC, Perederey commented on cmd/agent/main.go
> +		errClose := body.Body.Close()
Заморочено, можно просто defer body.Body.Close 

И лучше тогда результат выдачи назвать payload.

Будет payload.Body.Close()

2024-05-31 07:34 UTC, Perederey commented on cmd/agent/main.go
> +	config.InitAgentConfig()
Config.New() - так будет в стиле гоу

2024-05-31 07:34 UTC, Perederey commented on cmd/server/main.go
> +		err := storage.LocalNewMemStorageGauge.SetGauge(nameMet, valueMet)
Так не надо, ты каждый раз созидаешь что-ли все? Луш к передавать через паттерн Dependency Injection

2024-05-31 07:34 UTC, Perederey commented on cmd/server/main.go
> +		ticker := time.NewTicker(time.Duration(storeInterval) * time.Second)
Хех, ну так конечно можно, но не совсем. У тебя должен быть тикер и в нем функция сохранения, а сейчас у тебя наоборот

2024-05-31 07:34 UTC, Perederey commented on internal/handlers/JsonHandler.go
> +		valueMet := tModel.GetDelta()
Дублирование кода

2024-06-11 05:16 UTC, merged