Iter13
andrey67895/new_test_go_y_practicum pull request #15
Opened 2024-06-11 09:30 UTC by andrey67895

2024-06-17 19:37 UTC, avhitrov requested changes
Не совсем верно понято задание.
```
Перепишите сервис так, чтобы СУБД PostgreSQL стала хранилищем сокращённых URL вместо текущей реализации.
```
Это означает, что СУБД должна встроиться не вместо файлового хранилища, которое прилагалось к in-memory хранилищу, а вместо всей связки память-файл. Вкратце:
1. Должен быть описан общий интерфейс для хранилища. 
2. Связка in-memory+файл должна уйти в отдельный пакет, который будет реализовывать описанный интерфейс. Функции сброса в файл, горутина синхронизации должны уйти под капот этого пакета
3. Должен быть создан отдельный пакет, реализующий описанный интерфейс, но на базе СУБД. Под капот инициализации пакета должна быть спрятана инициализация структуры БД.
4. Оба пакета должны реализовывать весь набор функционала (можно даже сделать в in-memory заглушку для ping).
5. В процедуре общей инициализации на базе переданных параметров должно приниматься решение, какой из стораджей инициализировать и в каком объеме. Можно даже релизовать fallback в случае недоступности БД или неверных данных для инициализации БД.
6. Инициализированный сторадж в виде интерфейса должен быть передан в http-хендлеры.

+ замечания по организации агента - в комментариях к коду.

2024-06-17 19:37 UTC, avhitrov commented on cmd/agent/main.go
>  		count.ClearCount()
```suggestion
		err := retrySendRequestJSONFloatAll(host, tJSON)
		if err != nil {
			continue
		}
		err = retrySendRequestJSONInt(host, "counter", count.GetName(), count.GetMetrics())
		if err != nil {
			continue
		}
		count.ClearCount()
```
во всех случаях надо ловить (и, возможно, логировать) ошибку. Счетчик сбрасывается только в случае успешной отправки всех метрик. Ну или, как минимум, после успешной отправки самого счетчика.

2024-06-17 19:37 UTC, avhitrov commented on cmd/agent/main.go
> +func retrySendRequestJSONFloatAll(host string, tJSON []model.JSONMetrics) {
```suggestion
func retrySendRequestJSONFloatAll(host string, tJSON []model.JSONMetrics) error {
```

2024-06-17 19:37 UTC, avhitrov commented on cmd/agent/main.go
> +	}
```suggestion
	}
	return err
```

2024-06-24 10:20 UTC, andrey67895 commented on cmd/agent/main.go
>  		count.ClearCount()
Исправлено

2024-06-24 10:20 UTC, andrey67895 commented on cmd/agent/main.go
> +func retrySendRequestJSONFloatAll(host string, tJSON []model.JSONMetrics) {
Исправлено

2024-06-24 10:20 UTC, andrey67895 commented on cmd/agent/main.go
> +	}
Исправлено

2024-06-28 22:19 UTC, avhitrov commented on cmd/agent/main.go
>  		count.ClearCount()
+

2024-06-28 22:31 UTC, avhitrov requested changes
Реализация верная. Осталось правильно пробросить контекст в сторадж - замечания в комментариях к коду.

2024-06-28 22:31 UTC, avhitrov commented on internal/storage/StorageData.go
> +	GetCounter(id string) (int64, error)
```suggestion
	GetCounter(ctx context.Context, id string) (int64, error)
```

2024-06-28 22:31 UTC, avhitrov commented on internal/storage/StorageData.go
> +	GetGauge(id string) (float64, error)
```suggestion
	GetGauge(ctx context.Context, id string) (float64, error)
```

2024-06-28 22:31 UTC, avhitrov commented on internal/storage/StorageData.go
> +	GetData() (string, error)
```suggestion
	GetData(ctx context.Context) (string, error)
```

2024-06-28 22:31 UTC, avhitrov commented on internal/storage/InMemoryStorage.go
> +func (mem InMemStorage) GetData() (string, error) {
```suggestion
func (mem InMemStorage) GetData(_ context.Context, ) (string, error) {
```

2024-06-28 22:31 UTC, avhitrov commented on internal/storage/DBStorage.go
> +func (db DBStorage) SaveCounterInDB(id string, value int64) error {
```suggestion
func (ctx context.Context, db DBStorage) SaveCounterInDB(id string, value int64) error {
```

2024-06-28 22:31 UTC, avhitrov commented on internal/storage/DBStorage.go
> +	ctx := context.Background()
Контекст необходимо брать из запроса (`r.Context()`), это касается всех функций стораджа, работающих с данными. Для инициализации (если нужен контекст), его можно объявить в main и пробрасывать оттуда.

2024-06-28 22:31 UTC, avhitrov commented on internal/handlers/JsonHandler.go
>  		}
Этот код уместно перенести в мидлваре

2024-07-02 04:55 UTC, andrey67895 commented on internal/handlers/JsonHandler.go
>  		}
Перенес, дублирование везде убрал

2024-07-02 04:55 UTC, andrey67895 commented on internal/storage/DBStorage.go
> +	ctx := context.Background()
Исправил

2024-07-02 04:55 UTC, andrey67895 commented on internal/storage/DBStorage.go
> +func (db DBStorage) SaveCounterInDB(id string, value int64) error {
Исправил

2024-07-02 04:55 UTC, andrey67895 commented on internal/storage/InMemoryStorage.go
> +func (mem InMemStorage) GetData() (string, error) {
Исправил

2024-07-02 04:55 UTC, andrey67895 commented on internal/storage/StorageData.go
> +	GetData() (string, error)
Исправил

2024-07-02 04:55 UTC, andrey67895 commented on internal/storage/StorageData.go
> +	GetGauge(id string) (float64, error)
Исправил

2024-07-02 04:55 UTC, andrey67895 commented on internal/storage/StorageData.go
> +	GetCounter(id string) (int64, error)
Исправил

2024-07-04 22:19 UTC, avhitrov approved these changes
Все ок.

2024-07-05 03:20 UTC, merged