Iter15
andrey67895/new_test_go_y_practicum pull request #18
Opened 2024-07-02 08:55 UTC by andrey67895

2024-07-09 21:42 UTC, avhitrov requested changes
Не в полной мере реализовано задание как в агенте (нет паралаллельной отправки в несколько воркеров), так и в серверной (нет проверки подписи в запросе).

2024-07-09 21:42 UTC, avhitrov commented on cmd/agent/main.go
> +	err := metrics.SetDataMetrics(name, model.NewGauge(name, getMemByStats(name)))
Данная функция никогда не создает условие для ошибки. Внутри только блокировка, присвоение и снятие блокировки. Для чего тащить багаж с возвращаемой ошибкой?

2024-07-09 21:42 UTC, avhitrov commented on cmd/agent/main.go
> +			go worker(statName, results)
Нет никакого смысла открывать кучу горутин, каждая из которых занимается открытием и закрытием блокировки и элементарным присвоением. Операции Lock и Unlock довольно тяжеловесны, особенно на фоне работы с мапой. Гораздо эффективней поставить блокировку, затем заполнить мапу, потом снять блокировку и сделать это все в рамках одной горутины.
Если уж и устраивать конкуренцию, то между двумя горутинами, одна из которых заполняет данными из getMemByStats, вторая - getMemByGopsutil. Синхронизировать их можно с помощью WaitGroup.

2024-07-09 21:42 UTC, avhitrov commented on cmd/agent/main.go
>  }
В соответствии с заданием необходимо было откатиться на отправку метрик по одной за раз, но при этом сделать эту отправку в несколько сопел, количество воркеров должно определяться переменной `RateLimit`. Переменная честно заполняется, но далее нигде не используется. Необходимо реализовать эту часть ТЗ.

2024-07-09 21:42 UTC, avhitrov commented on internal/handlers/Crypto.go
> +func WithCrypto(h http.Handler) http.Handler {
Эта мидлварь работает на подпись ответов. Должна быть еще одна, которая работает на проверку запросов.

2024-07-10 03:54 UTC, andrey67895 commented on cmd/agent/main.go
> +	err := metrics.SetDataMetrics(name, model.NewGauge(name, getMemByStats(name)))
Согласен, убрал

2024-07-10 03:54 UTC, andrey67895 commented on cmd/agent/main.go
> +			go worker(statName, results)
Создал отдельный метод на это, исправил

2024-07-10 04:58 UTC, andrey67895 commented on cmd/agent/main.go
>  }
Готово

2024-07-10 05:05 UTC, andrey67895 commented on internal/handlers/Crypto.go
> +func WithCrypto(h http.Handler) http.Handler {
Добавил

2024-07-10 22:20 UTC, avhitrov requested changes
Особенность требований задания к данной итерации действительно состоит в том, что, если даже `HashKeyServer` установлен в непустое значение, то при отсутствии заголовка проверять валидность хеша не надо. Но если заголовок таки установлен в непустое значение, его необходимо проверить.

С комментарием к агенту достаточно просто ознакомиться, переделывать в нем ничего не нужно, и так нормально все.

2024-07-10 22:20 UTC, avhitrov commented on cmd/agent/main.go
>  		}
Решение годное! Есть только один тонкий момент, не блокер. Если ошибка возникнет не при отправке счетчика, то функция закончит свою работу и счетчик не будет сброшен. При этом горутины отстреляются до победного. Правильным решением здесь, наверное, будет сбор всех ошибок и анализ - был ли отправлен счетчик или нет. Но это если совсем придираться.

2024-07-10 22:20 UTC, avhitrov commented on internal/handlers/Crypto.go
> +			}
Особенность требований задания к данной итерации действительно состоит в том, что, если даже `HashKeyServer` установлен в непустое значение, то при отсутствии заголовка проверять валидность хеша не надо. Но если заголовок таки установлен в непустое значение, его необходимо проверить.

2024-07-11 04:33 UTC, andrey67895 commented on internal/handlers/Crypto.go
> +			}
Ага, теперь понял, исправил

2024-07-11 04:35 UTC, andrey67895 commented on cmd/agent/main.go
>  		}
Переделывать не стал, но понял)

2024-07-14 22:25 UTC, avhitrov approved these changes
Все ок!

2024-08-14 06:10 UTC, merged