Iter18
andrey67895/new_test_go_y_practicum pull request #20
Opened 2024-08-21 05:48 UTC by andrey67895

2024-08-26 22:56 UTC, avhitrov requested changes
Тесты ok, Документирование ok. Не вижу присоединенных pprof, предлагаю причесать импорты.

2024-08-26 22:56 UTC, avhitrov commented on internal/router/router.go
>  	"github.com/go-chi/chi/v5/middleware"
Предлагаю пройтись по всем модулям и причесать импорты в соответствии с рекомендациями gofumpt (goimports): https://t.me/bushigo/27

2024-08-28 17:11 UTC, andrey67895 commented on internal/router/router.go
>  	"github.com/go-chi/chi/v5/middleware"
pprof сделал, добавил профили. Упустил, спасибо!
импорты причесал:)

2024-08-29 21:45 UTC, avhitrov approved these changes
Все отлично!

2024-08-30 14:16 UTC, merged