Iter5
andrey67895/new_test_go_y_practicum pull request #7
Opened 2024-04-05 02:03 UTC by andrey67895

2024-04-08 21:19 UTC, avhitrov requested changes
Гонки данных в агенте и сервере. Необходимо проверять пользовательский ввод.

2024-04-08 21:19 UTC, avhitrov commented on cmd/agent/main.go
> +		reportInterval, _ = strconv.Atoi(envReportInterval)
Во всех случаях, когда мы имеем с пользовательским вводом, необходимо проверять ошибку. В данном случае при выпадении ошибки можно смело падать по log.Fatal.

2024-04-08 21:19 UTC, avhitrov commented on cmd/agent/main.go
> +var metrics = make(map[string]model.Gauge)
Мапа - потоконебезопасная конструкция. При конкурентном доступе к ней чтение и запись необходимо защищать блокировками. Например, sync.Mutex. В данном случае мы имеем Data Race condition:
```
==================
WARNING: DATA RACE
Read at 0x0001404176b8 by goroutine 8:
  github.com/andrey67895/new_test_go_y_practicum/internal/model.(*Count).GetMetrics()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/internal/model/MemModel.go:32 +0x74
  main.sendMetrics()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:41 +0x86
  main.main.func2()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:79 +0x4f

Previous write at 0x0001404176b8 by goroutine 7:
  github.com/andrey67895/new_test_go_y_practicum/internal/model.(*Count).UpdateCountPlusOne()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/internal/model/MemModel.go:16 +0x5c
  main.updateMetrics()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:30 +0x38
  main.main.func1()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:78 +0x33

Goroutine 8 (running) created at:
  main.main()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:79 +0x3cf

Goroutine 7 (running) created at:
  main.main()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:78 +0x30c
==================
Post "http://localhost:8080/update/counter/PollCount/5": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
==================
WARNING: DATA RACE
Write at 0x00c00001c930 by goroutine 7:
  runtime.mapassign_faststr()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/runtime/map_faststr.go:203 +0x0
  main.updateMetrics()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:28 +0x133
  main.main.func1()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:78 +0x33

Previous read at 0x00c00001c930 by goroutine 8:
  runtime.mapiternext()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/runtime/map.go:867 +0x0
  main.sendMetrics()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:38 +0x204
  main.main.func2()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:79 +0x4f

Goroutine 7 (running) created at:
  main.main()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:78 +0x30c

Goroutine 8 (running) created at:
  main.main()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:79 +0x3cf
==================
==================
WARNING: DATA RACE
Read at 0x0001404176b8 by goroutine 7:
  github.com/andrey67895/new_test_go_y_practicum/internal/model.(*Count).UpdateCountPlusOne()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/internal/model/MemModel.go:16 +0x44
  main.updateMetrics()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:30 +0x38
  main.main.func1()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:78 +0x33

Previous write at 0x0001404176b8 by goroutine 8:
  github.com/andrey67895/new_test_go_y_practicum/internal/model.(*Count).ClearCount()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/internal/model/MemModel.go:20 +0xc4
  main.sendMetrics()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:42 +0xb7
  main.main.func2()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:79 +0x4f

Goroutine 7 (running) created at:
  main.main()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:78 +0x30c

Goroutine 8 (running) created at:
  main.main()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/agent/main.go:79 +0x3cf
==================
```
Кстати, то же касается и счетчика. Судя по ошибкам, мы тоже ловим на доступе к структуре счетчика гонки.

2024-04-08 21:19 UTC, avhitrov commented on internal/storage/MemStorage.go
> +	data map[string]float64
То же самое, что и для агента. Незащищенная мапа приводит к гонкам при конкурентном доступе (а http-сервер априори является конкурентной средой, каждый хендлер обрабатывает запрос в отдельной горутине). Подробнее: https://t.me/bushigo/24
```
==================
WARNING: DATA RACE
Write at 0x00c00010a030 by goroutine 7:
  runtime.mapassign_faststr()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/runtime/map_faststr.go:203 +0x0
  github.com/andrey67895/new_test_go_y_practicum/internal/storage.(*MemStorageGauge).SetGauge()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/internal/storage/MemStorage.go:30 +0x125
  github.com/andrey67895/new_test_go_y_practicum/internal/handlers.MetHandler()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/internal/handlers/MetHandlers.go:69 +0xde
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x544
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5/middleware.Recoverer.func1()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/recoverer.go:45 +0x10d
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5/middleware.init.0.RequestLogger.func1.1()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/logger.go:55 +0x24a
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5/middleware.RealIP.func1()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/realip.go:36 +0xcc
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x67b
  net/http.serverHandler.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2938 +0x2a1
  net/http.(*conn).serve()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2009 +0xc24
  net/http.(*Server).Serve.func3()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x4f

Previous read at 0x00c00010a030 by goroutine 1067:
  runtime.mapiternext()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/runtime/map.go:867 +0x0
  github.com/andrey67895/new_test_go_y_practicum/internal/handlers.GetAll()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/internal/handlers/MetHandlers.go:12 +0xb5
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x544
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5/middleware.Recoverer.func1()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/recoverer.go:45 +0x10d
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5/middleware.init.0.RequestLogger.func1.1()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/logger.go:55 +0x24a
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5/middleware.RealIP.func1()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/realip.go:36 +0xcc
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x67b
  net/http.serverHandler.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2938 +0x2a1
  net/http.(*conn).serve()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2009 +0xc24
  net/http.(*Server).Serve.func3()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x4f

Goroutine 7 (running) created at:
  net/http.(*Server).Serve()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x86c
  net/http.(*Server).ListenAndServe()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2985 +0xbc
  net/http.ListenAndServe()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3239 +0x78f
  main.main()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/server/main.go:28 +0x672

Goroutine 1067 (running) created at:
  net/http.(*Server).Serve()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x86c
  net/http.(*Server).ListenAndServe()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2985 +0xbc
  net/http.ListenAndServe()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3239 +0x78f
  main.main()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/cmd/server/main.go:28 +0x672
==================
==================
WARNING: DATA RACE
Write at 0x00c000270568 by goroutine 7:
  github.com/andrey67895/new_test_go_y_practicum/internal/storage.(*MemStorageGauge).SetGauge()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/internal/storage/MemStorage.go:30 +0x134
  github.com/andrey67895/new_test_go_y_practicum/internal/handlers.MetHandler()
      D:/work/src/github.com/andrey67895/new_test_go_y_practicum/internal/handlers/MetHandlers.go:69 +0xde
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x544
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5/middleware.Recoverer.func1()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/recoverer.go:45 +0x10d
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5/middleware.init.0.RequestLogger.func1.1()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/logger.go:55 +0x24a
  net [...]

2024-04-08 21:19 UTC, avhitrov commented on internal/storage/MemStorage.go
> +	return e.data
Смотри https://t.me/bushigo/24 (Иллюзия третья)

2024-04-11 19:14 UTC, andrey67895 commented on internal/storage/MemStorage.go
> +	return e.data
Изучил, исправил

2024-04-11 19:14 UTC, andrey67895 commented on internal/storage/MemStorage.go
> +	data map[string]float64
Исправил

2024-04-11 19:14 UTC, andrey67895 commented on cmd/agent/main.go
> +var metrics = make(map[string]model.Gauge)
Исправил

2024-04-15 22:48 UTC, avhitrov approved these changes
Все замечания устранены. В будущем просьба не резолвить мои комментарии, если код отправлен на доработку. Я потом по ним проверяю суть вопроса и состав исправлений.

2024-04-22 17:26 UTC, merged